development:
  adapter: postgresql
  database: fastly_todo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fastly_todo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fastly_todo_production
  pool: 5
  timeout: 5000
